apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kc5p9yafr-python
  janus-idp.io/tekton: kc5p9yafr-python
  backstage.io/kubernetes-id: kc5p9yafr-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kc5p9yafr-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
