apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: kc5p9yafr-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kc5p9yafr-python 
  name: kc5p9yafr-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: kc5p9yafr-python
    weight: 100 
