apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kc5p9yafr-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kc5p9yafr-python 
  name: kc5p9yafr-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: kc5p9yafr-python 
